<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="8.18.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\CROSS.LOGGER\CROSS.LOGGER.csproj" />
	  <ProjectReference Include="..\CROSS.SECRYPT\CROSS.SECRYPT.csproj" />
	</ItemGroup>
</Project>
