<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\CROSS.APIREST\CROSS.APIREST.csproj" />
		<ProjectReference Include="..\CROSS.AUTH.TOKEN\CROSS.AUTH.TOKEN.csproj" />
		<ProjectReference Include="..\CROSS.LOGGER\CROSS.LOGGER.csproj" />
		<ProjectReference Include="..\CROSS.SECRYPT\CROSS.SECRYPT.csproj" />
	</ItemGroup>

</Project>
